export const cards = [
  {
    id: 1,
    ubicacion: "Av. Garay 111",
    precio: 1000000,
    img: "https://picsum.photos/700/300",
    ambientes: 2,
    baños: 1,
    dormitorios: 2,
    garage: 0,
    superficieTotal: 1111,
    superficieCubierta: 222,
    tipo: "alquiler",
    linkML: "",
    linkZonaprop: "",
    linkArgenprop: "",
  },
  {
    id: 2,
    ubicacion: "Entre Rios 222",
    precio: 2000000,
    img: "https://picsum.photos/700/300",
    ambientes: 4,
    baños: 2,
    dormitorios: 3,
    garage: 1,
    superficieTotal: 3333,
    superficieCubierta: 4444,
    tipo: "alquiler",
    linkML: "",
    linkZonaprop: "",
    linkArgenprop: "",
  },
  {
    id: 3,
    ubicacion: "LDZ 333",
    precio: 4000000,
    img: "https://picsum.photos/700/300",
    ambientes: 1,
    baños: 3,
    dormitorios: 3,
    garage: 1,
    superficieTotal: 777,
    superficieCubierta: 888,
    tipo: "venta",
    linkML: "",
    linkZonaprop: "",
    linkArgenprop: "",
  },
  {
    id: 4,
    ubicacion: "Copenague 101",
    precio: 1000000,
    img: "https://picsum.photos/700/300",
    ambientes: 1,
    baños: 3,
    dormitorios: 3,
    garage: 1,
    superficieTotal: 900,
    superficieCubierta: 990,
    tipo: "pozo",
    linkML: "",
    linkZonaprop: "",
    linkArgenprop: "",
  },
  {
    id: 5,
    ubicacion: "Paraguay 292",
    precio: 1000000,
    img: "https://picsum.photos/700/300",
    ambientes: 1,
    baños: 3,
    dormitorios: 3,
    garage: 1,
    superficieTotal: 900,
    superficieCubierta: 990,
    tipo: "preventa",
    linkML: "",
    linkZonaprop: "",
    linkArgenprop: "",
  },
  {
    id: 6,
    ubicacion: "Uruguay 393",
    precio: 1000000,
    img: "https://picsum.photos/700/300",
    ambientes: 1,
    baños: 3,
    dormitorios: 3,
    garage: 1,
    superficieTotal: 900,
    superficieCubierta: 990,
    tipo: "en construccion",
    meli: "",
    zonaprop: "",
    argenprop: "",
  },
];
